## **Handling Imbalanced Dataset**
There are two techniques of Handling imbalanced dataset. 
* **Up Sampling** -> Here we increase the less class datapoints.
* **Down Sampling** -> Here we decrease the high class datapoints.

In [2]:
import pandas as pd 
import numpy as np

In [6]:
## Selecting random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classses

n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples*class_0_ratio)
n_class_1 = n_samples - n_class_0

In [9]:
n_class_0,n_class_1

(900, 100)

`Creating my DataFrame with Imbalanced Data`

In [ ]:
class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0] * n_class_0
})
class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1] * n_class_1
})

In [14]:
class_0

     feature_1  feature_2  target
0    -1.085631   0.551302       0
1     0.997345   0.419589       0
2     0.282978   1.815652       0
3    -1.506295  -0.252750       0
4    -0.578600  -0.292004       0
..         ...        ...     ...
895   0.238761  -0.003155       0
896  -1.106386  -0.430660       0
897   0.366732  -0.146416       0
898   1.023906   1.160176       0
899  -0.210056  -0.641512       0

[900 rows x 3 columns]

In [15]:
class_1

    feature_1  feature_2  target
0    1.699768   2.139033       1
1    1.367739   2.025577       1
2    1.795683   1.803557       1
3    2.213696   3.312255       1
4    3.033878   3.187417       1
..        ...        ...     ...
95   1.376371   2.845701       1
96   2.239810   0.880077       1
97   1.131760   1.640703       1
98   2.902006   0.390305       1
99   2.697490   2.013570       1

[100 rows x 3 columns]

In [18]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [19]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [20]:
df.target.value_counts()

target
0    900
1    100
Name: count, dtype: int64

### `upsampling` 
* Increasing the less number of class samples

In [22]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [23]:
from sklearn.utils import resample

df_minority_upsampled = resample(df_minority,replace=True, # sample with replacement
                        n_samples=len(df_majority),
                        random_state=42
                        )

In [24]:
df_minority.shape

(100, 3)

In [ ]:
df_minority_upsampled.shape  # this is how we upsample the minority class

(900, 3)

In [26]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [27]:
## Now we can combine majority with minority 

df_upsampled = pd.concat([df_majority,df_minority_upsampled])

In [28]:
df_upsampled.shape

(1800, 3)

#### `DownSampling`

In [29]:
## Now the same above dataset 


class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0] * n_class_0
})
class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1] * n_class_1
})

In [31]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [32]:
df.shape

(1000, 3)

In [33]:
class_0 = df[df['target']==0]
class_1 = df[df['target']==1]

In [35]:
class_0.shape,class_1.shape

((900, 3), (100, 3))

In [38]:
from sklearn.utils import resample

df_majority_downsampled = resample(df_majority,replace=False,
                            n_samples=len(df_minority),
                            random_state=42
                            )

In [39]:
df_majority_downsampled

     feature_1  feature_2  target
70    0.468439   1.720920       0
827   1.089165  -0.464899       0
231   0.753869  -0.969798       0
588   0.588686  -0.704720       0
39    0.283627   1.012868       0
..         ...        ...     ...
398  -0.168426   0.553775       0
76   -0.403366   0.081491       0
196  -0.269293   0.611238       0
631  -0.295829   0.671673       0
751  -0.553404   0.804438       0

[100 rows x 3 columns]

In [40]:
df_downsampled = pd.concat([df_minority,df_majority_downsampled])

In [41]:
df_downsampled

     feature_1  feature_2  target
900   1.699768   2.139033       1
901   1.367739   2.025577       1
902   1.795683   1.803557       1
903   2.213696   3.312255       1
904   3.033878   3.187417       1
..         ...        ...     ...
398  -0.168426   0.553775       0
76   -0.403366   0.081491       0
196  -0.269293   0.611238       0
631  -0.295829   0.671673       0
751  -0.553404   0.804438       0

[200 rows x 3 columns]