## **DATA ENCODING**

- 1.Nominal/OHE Encoding
- 2.Label and Ordinal Encoding
- 3.Target Guided Ordinal Encoding

### **Nominal/OHE Encoding**

One hot encoding also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique each category is represented as a binary vector where each bit corresponds to a unique category. For example if we have a categorical variable "color" with three possible values `red , green and blue` we can represent it in one hot encoding as follows:

1. Blue: [1,0,0]
1. Green: [0,1,0]
1. Red: [0,0,1]

In [15]:
import pandas as pd

In [16]:
df = pd.DataFrame({
    'colors':['red','green','blue','blue','green','red','blue']
})

In [17]:
df

  colors
0    red
1  green
2   blue
3   blue
4  green
5    red
6   blue

In [18]:
# ONE HOT ENCODING 
from sklearn.preprocessing import OneHotEncoder

In [26]:
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['colors']]).toarray()

In [27]:
encoded

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [28]:
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [29]:
encoder_df

   colors_blue  colors_green  colors_red
0          0.0           0.0         1.0
1          0.0           1.0         0.0
2          1.0           0.0         0.0
3          1.0           0.0         0.0
4          0.0           1.0         0.0
5          0.0           0.0         1.0
6          1.0           0.0         0.0

In [30]:
## Concatinating with original df 

new_df = pd.concat([df,encoder_df],axis=1)

In [31]:
new_df

  colors  colors_blue  colors_green  colors_red
0    red          0.0           0.0         1.0
1  green          0.0           1.0         0.0
2   blue          1.0           0.0         0.0
3   blue          1.0           0.0         0.0
4  green          0.0           1.0         0.0
5    red          0.0           0.0         1.0
6   blue          1.0           0.0         0.0

### Applying on Real DataSet

In [34]:
import seaborn as sns

tip_df = sns.load_dataset('tips')

In [35]:
tip_df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### **Encoding the day column**

In [40]:
tip_df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [37]:
encoder = OneHotEncoder()

encoded = encoder.fit_transform(tip_df[['day']]).toarray()

In [39]:
encoded.shape

(244, 4)

In [42]:
encoded[:15]

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

In [43]:
## To make a dataframe
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
encoder_df

     day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [44]:
## Concatinating with original Data
new_tips_df =pd.concat([tip_df,encoder_df],axis=1)

In [45]:
new_tips_df.head()

,total_bill,tip,sex,smoker,day,time,size,day_Fri,day_Sat,day_Sun,day_Thur
0,16.99,1.01,Female,No,Sun,Dinner,2,0.0,0.0,1.0,0.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0.0,0.0,1.0,0.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0.0,0.0,1.0,0.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0.0,0.0,1.0,0.0
4,24.59,3.61,Female,No,Sun,Dinner,4,0.0,0.0,1.0,0.0

In [ ]:
# if we have new data to encode 
import warnings 
warnings.filterwarnings('ignore')


encoder.transform([['Sun']]).toarray()

array([[0., 0., 1., 0.]])

* This is done only for a single column `day` it need to apply all the `categorical column` in the dataset `before feding into the model`.