## **Label Encoding and Ordinal Encoding**

### `Label Encoding`
* Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data.

* Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. `For example` if we have a category `"colors"` with three possible values "Red", "Green", "Blue". we can assign label in this way.

1. Blue = 1
2. Green = 2
3. Red = 3

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "colors":['Red','Green','Red','Blue','Blue','Green','Blue','Red','Green']
})
df

  colors
0    Red
1  Green
2    Red
3   Blue
4   Blue
5  Green
6   Blue
7    Red
8  Green

In [3]:
from sklearn.preprocessing import LabelEncoder

In [7]:
lb_encoder = LabelEncoder()
lb_encoder.fit_transform(df[['colors']])

d:\University\DataScience\Specialization\venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 1, 2, 0, 0, 1, 0, 2, 1])

In [8]:
lb_encoder.transform([['Red']])

d:\University\DataScience\Specialization\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [9]:
lb_encoder.transform([['Green']])

d:\University\DataScience\Specialization\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [11]:
lb_encoder.transform([['Blue']])

d:\University\DataScience\Specialization\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [ ]:
## Encoding the label 

df['colors_label_encode'] = lb_encoder.transform(df['colors'])

In [14]:
df

  colors  colors_label_encode
0    Red                    2
1  Green                    1
2    Red                    2
3   Blue                    0
4   Blue                    0
5  Green                    1
6   Blue                    0
7    Red                    2
8  Green                    1

`Problem with Label Encoding: `
* If the categories has some order, at that time we can't use `label encoder` because it is not a good techniques for that time.
`Solution:`
* To encoder the ordinal data , mean if the data has some order like T-shirt size can be `small` -> `Medium`-> `Large`. We can use `Ordinal Encoding.`

### **Ordinal Encoding**

In ordinal Encoding we assign highest value to the high rank category and lowest to the low rank category. like `small`=1, `medium`=2, and `large`=3

In [44]:
df1 = pd.DataFrame({
    'Education Level':['M','FSC','BS','MS','M','PhD','PhD']
})

df1

  Education Level
0               M
1             FSC
2              BS
3              MS
4               M
5             PhD
6             PhD

In [35]:
from sklearn.preprocessing import OrdinalEncoder

or_encoder = OrdinalEncoder(categories=[['M','FSC','BS','MS','PhD']])

In [36]:
encoded = or_encoder.fit_transform(df1[['Education Level']])

In [37]:
encoded

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [4.],
       [4.]])

In [38]:
encoded_df = pd.DataFrame(
    encoded,
    columns=or_encoder.get_feature_names_out(['Education Level']),
    index=df1.index
)

In [39]:
encoded_df

   Education Level
0              0.0
1              1.0
2              2.0
3              3.0
4              0.0
5              4.0
6              4.0

That is how we can apply Ordinal Encoding

In [42]:
df1['Education ordinal Encode'] = or_encoder.transform(df1[['Education Level']])

In [43]:
df1

  Education Level  Education ordinal Encode
0               M                       0.0
1             FSC                       1.0
2              BS                       2.0
3              MS                       3.0
4               M                       0.0
5             PhD                       4.0
6             PhD                       4.0

In [48]:
new_df = pd.concat([df1,encoded_df],axis=1)

In [49]:
new_df

   Education Level  Education Level
0                M              0.0
1              FSC              1.0
2               BS              2.0
3               MS              3.0
4                M              0.0
5              PhD              4.0
6              PhD              4.0