## **Target Guided Encoding in Ordinal Way**
* It is a technique used to encode `categorical variables` based on their relationship with the target variable. This encoding techniques is useful when we have a categorical variable with `large number of unique categories`, and we want to use this variable as a feature in our machine learning model.

* In Target Ordinal Encoding we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This create a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'Education':['M','Phd','Phd','MS','BS','M','MS','BS'],
    'salary':[100,1000,1200,700,300,250,500,400]
})

In [3]:
df

  Education  salary
0         M     100
1       Phd    1000
2       Phd    1200
3        MS     700
4        BS     300
5         M     250
6        MS     500
7        BS     400

`Target Guided Encoding`

In [7]:
## first of all we group the data
mean_salary = df.groupby('Education')['salary'].mean().to_dict()
mean_salary

{'BS': 350.0, 'M': 175.0, 'MS': 600.0, 'Phd': 1100.0}

In [9]:
df['Education_encode'] = df['Education'].map(mean_salary)

In [10]:
df

  Education  salary  Education_encode
0         M     100             175.0
1       Phd    1000            1100.0
2       Phd    1200            1100.0
3        MS     700             600.0
4        BS     300             350.0
5         M     250             175.0
6        MS     500             600.0
7        BS     400             350.0

#### Now I can give only `two feature` to my model `for training purpose`

In [12]:
# the two features are 
df[['salary','Education_encode']]

   salary  Education_encode
0     100             175.0
1    1000            1100.0
2    1200            1100.0
3     700             600.0
4     300             350.0
5     250             175.0
6     500             600.0
7     400             350.0

In [13]:
import seaborn as sns

In [14]:
tips_df = sns.load_dataset('tips')

In [15]:
tips_df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [18]:
## Target Guided Ordinal encoding of Time with total bill

mean_total_bill = tips_df.groupby('time')['total_bill'].mean().to_dict()

C:\Users\PMYLS\AppData\Local\Temp\ipykernel_8484\3295244674.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_total_bill = tips_df.groupby('time')['total_bill'].mean().to_dict()

In [19]:
mean_total_bill

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [20]:
tips_df['time_encode_guided_oridinal'] = tips_df['time'].map(mean_total_bill)

In [23]:
tips_df

,total_bill,tip,sex,smoker,day,time,size,time_encode_guided_oridinal
0,16.99,1.01,Female,No,Sun,Dinner,2,20.797159
1,10.34,1.66,Male,No,Sun,Dinner,3,20.797159
2,21.01,3.50,Male,No,Sun,Dinner,3,20.797159
3,23.68,3.31,Male,No,Sun,Dinner,2,20.797159
4,24.59,3.61,Female,No,Sun,Dinner,4,20.797159
...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,20.797159
240,27.18,2.00,Female,Yes,Sat,Dinner,2,20.797159
241,22.67,2.00,Male,Yes,Sat,Dinner,2,20.797159
242,17.82,1.75,Male,No,Sat,Dinner,2,20.797159
243,18.78,3.00,Female,No,Thur,Dinner,2,20.797159

In [26]:
[var for var in tips_df.columns if tips_df[var].isnull().mean() < 0.05]

['total_bill',
 'tip',
 'sex',
 'smoker',
 'day',
 'time',
 'size',
 'time_encode_guided_oridinal']