## `Pandas DataFrame And Series`

* Pandas is a powerful data manipulation library in Python, widely used for `data analysis` and `data cleaning`. It provides two primary data structures: `Series` and `DataFrame`. A series is a one dimentional array like object, while a DataFrame is a two dimentional, size-mutable and potentially heterogenous tabular data structure with labeled axes (rows and columns)

`data manipulation: ` 
* mean modifying and organizing data to make it useful.
* It includes tasks like `filtering, sorting, grouping, cleaning, and transforming data`.

`Size-mutable`
* Size-mutable means a DataFrame can grow or shrink.
You can add or remove rows and columns after it is created.

`Potentially heterogeneous`
* Potentially heterogeneous means a DataFrame can contain different data types.
* For example, one column can have numbers, another text, and another dates.

In [22]:
import pandas as pd
import numpy as np

`Series`
* Series is a one dimentional array like object that can hold any data type. It is similar to a column in a table.

In [8]:
data = [1,2,3,4,5]

series = pd.Series(data)
print('Series\n',series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

* `Creating series from dictionary element`

In [ ]:
data = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data)   # here the keys will be considered as index and values will be value in series
print(series_dict)

a    1
b    2
c    3
dtype: int64

* `We can also give different index over here`

In [11]:
## another technique to create a series

data = [10,20,30,40]

index = ['A','B','C','D']   
pd.Series(data,index)

A    10
B    20
C    30
D    40
dtype: int64

## `DataFrame`
* In data frame we can have multiple `rows` and `columns`

In [13]:
## Creating a dataframe from a dictionary of lists

dict_of_list = {
    'shoaib':[12,34,56,77,98],
    'Alim':[44,55,23,41,21],
    'Kamil':[44,21,22,13,63]
}

print(dict_of_list)

pd.DataFrame(dict_of_list)

{'shoaib': [12, 34, 56, 77, 98], 'Alim': [44, 55, 23, 41, 21], 'Kamil': [44, 21, 22, 13, 63]}

   shoaib  Alim  Kamil
0      12    44     44
1      34    55     21
2      56    23     22
3      77    41     13
4      98    21     63

In [20]:
data = {
    'Name':['Shoaib','Kamil','Qais','Kashif'],
    'Age':[33,44,53,24],
    'City':['Peshawar','Karachi','Islamabad','Quetta']
}


df = pd.DataFrame(data)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

     Name  Age       City
0  Shoaib   33   Peshawar
1   Kamil   44    Karachi
2    Qais   53  Islamabad
3  Kashif   24     Quetta

In [23]:
## now you can convert this into an array also
np.array(df)

array([['Shoaib', 33, 'Peshawar'],
       ['Kamil', 44, 'Karachi'],
       ['Qais', 53, 'Islamabad'],
       ['Kashif', 24, 'Quetta']], dtype=object)

In [27]:
## Creating a dataframe from a list of Dictionaries
data = [
    {'Name':'Shoaib','Age':32,'City':'KPK'},
    {'Name':'Amin','Age':44,'City':'Islamabad'},
    {'Name':'Kashif','Age':35,'City':'Quetta'}
]
df1 = pd.DataFrame(data)
print(type(df1))
df1

<class 'pandas.core.frame.DataFrame'>

     Name  Age       City
0  Shoaib   32        KPK
1    Amin   44  Islamabad
2  Kashif   35     Quetta

### `How to Read Any kind of Dataset`

In [30]:
df = pd.read_csv('Absenteeism_data.csv')

In [31]:
df.head()

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [33]:
## Accessing data from dataframe
df1

     Name  Age       City
0  Shoaib   32        KPK
1    Amin   44  Islamabad
2  Kashif   35     Quetta

In [34]:
## Access only the 'Name' column
df1['Name']

0    Shoaib
1      Amin
2    Kashif
Name: Name, dtype: object

In [35]:
## Access only the 'City' column
df1['City']

0          KPK
1    Islamabad
2       Quetta
Name: City, dtype: object

In [36]:
## Access only the 'Age' column
df1['Age']

0    32
1    44
2    35
Name: Age, dtype: int64

In [37]:
## If we access a single column from data frame then it become a Series

type(df1['Age'])

pandas.core.series.Series

In [38]:
## If we want to access a row
df1.iloc[0]

Name    Shoaib
Age         32
City       KPK
Name: 0, dtype: object

In [42]:
df1.loc[2]

Name    Kashif
Age         35
City    Quetta
Name: 2, dtype: object

In [53]:
## Access the "Kashif" Name from the df
df1.iloc[2][0]

C:\Users\PMYLS\AppData\Local\Temp\ipykernel_14152\2158741113.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df1.iloc[2][0]

'Kashif'

In [52]:
df1.iloc[2].values[0]

'Kashif'

In [54]:
## Accessing a specified element

## get all the name
df1['Name']

0    Shoaib
1      Amin
2    Kashif
Name: Name, dtype: object

In [55]:
df1

     Name  Age       City
0  Shoaib   32        KPK
1    Amin   44  Islamabad
2  Kashif   35     Quetta

`df.at[index_no,in_colum]`

In [59]:
df1.at[1,'Age']

np.int64(44)

In [58]:
df1.at[2,'City']

'Quetta'

In [61]:
df1

     Name  Age       City
0  Shoaib   32        KPK
1    Amin   44  Islamabad
2  Kashif   35     Quetta

* Accessing a specified element using `iat`

In [63]:
df1.iat[0,0]  # it give us "Shoaib"

'Shoaib'

In [ ]:
df1.iat[2,2]  # it give us "Quetta"

'Quetta'

In [65]:
df1.iat[2,1]  # it give us "Shoaib"

np.int64(35)

`Data Manipulation with DataFrames`

In [66]:
df1

     Name  Age       City
0  Shoaib   32        KPK
1    Amin   44  Islamabad
2  Kashif   35     Quetta

In [67]:
# 1- How to add a new column
df1['Salary'] = [3000,40000,50000]
df1

     Name  Age       City  Salary
0  Shoaib   32        KPK    3000
1    Amin   44  Islamabad   40000
2  Kashif   35     Quetta   50000

In [71]:
# 2- If i want to remove a column
df1.drop('Salary',axis=1,inplace=True)

In [70]:
df1

     Name  Age       City  Salary
0  Shoaib   32        KPK    3000
1    Amin   44  Islamabad   40000
2  Kashif   35     Quetta   50000

In [72]:
# 3-Add age to the column
df1['Age'] = df1['Age']+1
df1

     Name  Age       City
0  Shoaib   33        KPK
1    Amin   45  Islamabad
2  Kashif   36     Quetta

In [74]:
df1.drop(0,inplace=True)

In [75]:
df1

     Name  Age       City
1    Amin   45  Islamabad
2  Kashif   36     Quetta

* Some important features

In [76]:
print('Data Type:',df1.dtypes)
print('Statistical Summary:',df1.describe())

Data Type: Name    object
Age      int64
City    object
dtype: object
Statistical Summary:              Age
count   2.000000
mean   40.500000
std     6.363961
min    36.000000
25%    38.250000
50%    40.500000
75%    42.750000
max    45.000000