# `Holiday Package Prediction`
## 1- Problem Statement
"Trips & Travel.com" Company wants to enable and establish a viable business model to expand the customer base. One of the ways to expand the customer base is to introduce a new offering of packages. Currently, there are `5 types` of packages the company is offering, `Basic`, `Standard`,`Deluxe`, `Super Deluxe`,`King`. Looking at the data of the last year, we observed that `18%` of the customers purchased the packages. However, the marketing cost was quite high because customers were contracted at random without looking at the available information. The company now planning to launch a new product i.e `Wellness Tourism Package.`  Wellness Tourism is defined as Travel that allows the traveler to maintain, enhance or kick-start a healthy lifestyle. and support or increase one's sense of well-being. However, this time company wants to harness the available data of existing and potential customers to make the marketing expenditure more efficient.


## 2- Data Collection
The Dataset is collected from  https://www.kaggle.com/datasets/susant4learning/holiday-package-purchase-prediction  The data consists of 20 column and 4888 rows.

In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# import plotly.express as px 
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [4]:
df = pd.read_csv('Travel.csv')
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

# `Aim`
The company wants to `launch new product by the name (wireless product)`, on the basis of given data we have to classify whether or not they launch the product.

# `Feature Engineering part-1`

### 1- Data Cleaning
1. Handling Missing Values
2. Handling Duplicate Values
3. Check data type
4. Understand the dataset

In [8]:
## checking missing value
df.isnull().sum().sort_values(ascending=False)

DurationOfPitch             251
MonthlyIncome               233
Age                         226
NumberOfTrips               140
NumberOfChildrenVisiting     66
NumberOfFollowups            45
PreferredPropertyStar        26
TypeofContact                25
CustomerID                    0
ProdTaken                     0
Gender                        0
CityTier                      0
ProductPitched                0
NumberOfPersonVisiting        0
Occupation                    0
MaritalStatus                 0
PitchSatisfactionScore        0
Passport                      0
OwnCar                        0
Designation                   0
dtype: int64

1- `We have missing values in 8 columns see above`

In [9]:
## Checking issues in categorical columns as well as the count of each category
categorical_col = [col for col in df.columns if df[col].dtype =='O']
nummerical_col = [col for col in df.columns if df[col].dtype !='O']

In [ ]:
## these are the categorical columns 
categorical_col

['TypeofContact',
 'Occupation',
 'Gender',
 'ProductPitched',
 'MaritalStatus',
 'Designation']

In [11]:
### these are the numerical columns
nummerical_col

['CustomerID',
 'ProdTaken',
 'Age',
 'CityTier',
 'DurationOfPitch',
 'NumberOfPersonVisiting',
 'NumberOfFollowups',
 'PreferredPropertyStar',
 'NumberOfTrips',
 'Passport',
 'PitchSatisfactionScore',
 'OwnCar',
 'NumberOfChildrenVisiting',
 'MonthlyIncome']

In [12]:
### total number of categorical and numerical columns are 
print('Total categorical col:',len(categorical_col)) 
print('Total Numerical col:',len(nummerical_col))

Total categorical col: 6
Total Numerical col: 14

In [17]:
## Gender columns 
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

2-`The problem over here is Female category occur two times due to spelling mistakes, we need to combine them`

In [18]:
## 
print(categorical_col)

['TypeofContact', 'Occupation', 'Gender', 'ProductPitched', 'MaritalStatus', 'Designation']

In [19]:
## TypeofContract column
df['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [20]:
## 'Occupation' 
df['Occupation'].value_counts()

Occupation
Salaried          2368
Small Business    2084
Large Business     434
Free Lancer          2
Name: count, dtype: int64

In [21]:
### ProductPicted column
df['ProductPitched'].value_counts()

ProductPitched
Basic           1842
Deluxe          1732
Standard         742
Super Deluxe     342
King             230
Name: count, dtype: int64

In [ ]:
## Marital Status column
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

3. `The category 'single' and 'Unmarried' occur both we need to combine them as single category`

In [23]:
### Designation column
df['Designation'].value_counts()

Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64

- `Solution:`
`As above two categorical columns has issues, we now correct them`
1. Gender 
2. MaritalStatus

In [24]:
df['Gender'] = df['Gender'].replace('Fe Male','Female')
df['MaritalStatus'] = df['MaritalStatus'].replace('Single','Unmarried')

In [ ]:
 ## now the problem solved here
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [ ]:
## Here also the problem solved
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

### Checking Missing Values

In [31]:
## Checking missing values

feature_with_nan = [feature for feature in df.columns if df[feature].isnull().sum() >= 1]
for feature in feature_with_nan:
    print(feature,':',np.round(df[feature].isnull().mean()*100,5),'% Missing Values')

Age : 4.62357 % Missing Values
TypeofContact : 0.51146 % Missing Values
DurationOfPitch : 5.13502 % Missing Values
NumberOfFollowups : 0.92062 % Missing Values
PreferredPropertyStar : 0.53191 % Missing Values
NumberOfTrips : 2.86416 % Missing Values
NumberOfChildrenVisiting : 1.35025 % Missing Values
MonthlyIncome : 4.76678 % Missing Values

In [33]:
## Statistics on numerical columns (Null Cols)
df[feature_with_nan].select_dtypes(exclude='object').describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

### Imputing Null Values
1. Impute Median Values for `Age` column
2. Impute Mode for `Type of Contract`
3. Impute Median for `Duration of Pitch` 
4. Impute Mode for `NumberofFollowup` as it is `Descrete feature`(if categories is more than 10,20 30 etc that is called descrete feature)
5. Impute Mode for `PreferredPropertyStar`
6. Impute Median for `NumberofTrips`
7. Impute Mode for `NumberOfChildrenVisiting`
8. Impute Median for `MonthlyIncome`

In [43]:
## Age 
df.Age.fillna(df.Age.median(),inplace=True)

## TypeofContract
df.TypeofContact.fillna(df.TypeofContact.mode()[0],inplace=True)

## Duration of Pitch
df.DurationOfPitch.fillna(df.DurationOfPitch.median(),inplace=True)

## NumberOfFollowups
df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0],inplace=True)

## PreferredPropertyStar
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0],inplace=True)

## NumberOfTrips
df.NumberOfTrips.fillna(df.NumberOfTrips.median(),inplace=True)

## NumberOfChildrenVisiting
df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0],inplace=True)

## MonthlyIncome
df.MonthlyIncome.fillna(df.MonthlyIncome.median(),inplace=True)

In [44]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

### `As we have perfectly Fill the Missing Values in  Our Data Over Here Now`

In [45]:
df.columns

Index(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'ProductPitched', 'PreferredPropertyStar',
       'MaritalStatus', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore',
       'OwnCar', 'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

In [46]:
### As CustomerID column is not that important so we remove it 
df.drop('CustomerID',axis=1,inplace=True)

In [47]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

# **Feature Engineering**

### `Feature Extraction`

In [50]:
### Creating New Column for feature by combining two feature which also reduce the total no of columns
df['TotalVisiting'] = df['NumberOfChildrenVisiting'] + df['NumberOfPersonVisiting']

## Now we remove the two separate columns we don't need them anymore
df.drop(columns=['NumberOfChildrenVisiting','NumberOfPersonVisiting'],axis=1,inplace=True)

In [51]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [53]:
## to get the total Numerical feature 

nummerical_features = [feature for feature in df.columns if df[feature].dtype !='O']
print('Total Numerical Features are:',len(nummerical_features))

Total Numerical Features are: 12

In [54]:
## to get the total Categorical feature 

categorical_features = [feature for feature in df.columns if df[feature].dtype =='O']
print('Total Categorical Features are:',len(categorical_features))

Total Categorical Features are: 6

In [57]:
## Descrete Features 
discrete_features = [feature for feature in nummerical_features if len(df[feature].unique()) <=25]
print('Num of Descrete Features :',len(discrete_features))

Num of Descrete Features : 9

In [58]:
## Continuous Features 
continuous_features = [feature for feature in nummerical_features if feature not in discrete_features]
print('Continuous Features :',len(continuous_features))

Continuous Features : 3

In [59]:
### Now our dataframe look like this 
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [ ]:
## There are still Preprocessing needed