### **Stokes Prediction Continuation with SVC**

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv('../04. Logistic Regression\practice\Clean_Stokes_Data.csv')

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\PMYLS\AppData\Local\Temp\ipykernel_20548\2806983832.py:1: SyntaxWarning: invalid escape sequence '\p'
  df = pd.read_csv('../04. Logistic Regression\practice\Clean_Stokes_Data.csv')

In [3]:
df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,29.0,never smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [4]:
df['work_type'].value_counts()

work_type
Private          2925
Self-employed     819
children          687
Govt_job          657
Never_worked       22
Name: count, dtype: int64

In [5]:
df['smoking_status'].value_counts()

smoking_status
never smoked       1892
Unknown            1544
formerly smoked     885
smokes              789
Name: count, dtype: int64

In [6]:
## Label Encoding 
df['gender'] = df['gender'].map({'Male':1,'Female':0})

In [7]:
df['ever_married'] = df['ever_married'].map({'Yes':1,'No':0})
df['Residence_type'] = df['Residence_type'].map({'Urban':1,'Rural':0})

## **Nominal Encoding with OneHotEncoding**

In [8]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

encoded = ohe.fit_transform(df[['work_type','smoking_status']]).toarray()
encoded

array([[0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], shape=(5110, 9))

In [9]:
encoded_df = pd.DataFrame(encoded,columns=ohe.get_feature_names_out())
encoded_df.head()

,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [10]:
## concatinating original df and encoded df 
final_df  = pd.concat([df,encoded_df],axis=1)
final_df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,1.0,67.0,0,1,1,Private,1,228.69,36.6,formerly smoked,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,61.0,0,0,1,Self-employed,0,202.21,29.0,never smoked,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,1.0,80.0,0,1,1,Private,0,105.92,32.5,never smoked,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,49.0,0,0,1,Private,1,171.23,34.4,smokes,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,79.0,1,0,1,Self-employed,0,174.12,24.0,never smoked,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [11]:
## droping the two nominal columns  smoking_status and work_type
final_df.drop(columns=['work_type','smoking_status'],axis=1,inplace=True)

In [12]:
final_df.shape

(5110, 18)

In [13]:
final_df.sample(3)

,gender,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,stroke,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
4399,0.0,23.0,0,0,1,0,84.93,24.2,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2467,1.0,78.0,0,0,1,1,74.70,28.8,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
864,1.0,65.0,0,0,1,0,94.64,28.6,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [14]:
final_df.isnull().sum()

gender                            1
age                               0
hypertension                      0
heart_disease                     0
ever_married                      0
Residence_type                    0
avg_glucose_level                 0
bmi                               0
stroke                            0
work_type_Govt_job                0
work_type_Never_worked            0
work_type_Private                 0
work_type_Self-employed           0
work_type_children                0
smoking_status_Unknown            0
smoking_status_formerly smoked    0
smoking_status_never smoked       0
smoking_status_smokes             0
dtype: int64

In [15]:
final_df = final_df[~final_df['gender'].isna()]

In [16]:
final_df.isnull().sum()

gender                            0
age                               0
hypertension                      0
heart_disease                     0
ever_married                      0
Residence_type                    0
avg_glucose_level                 0
bmi                               0
stroke                            0
work_type_Govt_job                0
work_type_Never_worked            0
work_type_Private                 0
work_type_Self-employed           0
work_type_children                0
smoking_status_Unknown            0
smoking_status_formerly smoked    0
smoking_status_never smoked       0
smoking_status_smokes             0
dtype: int64

#### Now we will Scale some columns

In [17]:
X = final_df.drop('stroke',axis=1)
y = final_df['stroke']

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.2,random_state=42,stratify=y)

In [19]:
X_train.head(2)

,gender,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
845,0.0,48.0,0,0,1,1,69.21,33.1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3745,0.0,29.0,0,0,0,1,84.19,21.2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train[['age','avg_glucose_level','bmi']])
X_test_scaled = scaler.transform(X_test[['age','avg_glucose_level','bmi']])

In [21]:
X_train_scaled

array([[ 0.20939671, -0.82122128,  0.55163183],
       [-0.62984543, -0.48588352, -0.98253712],
       [-0.3648216 ,  0.30231691, -0.76337013],
       ...,
       [ 0.78361502, -0.60990029,  0.95128929],
       [-0.54150415, -0.7128745 , -0.36371267],
       [ 0.12105544, -1.12051807, -0.1316535 ]], shape=(4087, 3))

In [22]:
X_test_scaled

array([[-0.67401607, -0.49774794,  0.97707364],
       [-1.77828205, -0.28194981, -1.20170412],
       [ 0.43024991, -0.92889649,  0.28089613],
       ...,
       [-0.27648032, -0.33992877,  2.1889382 ],
       [-1.11572246, -0.5942303 , -0.6731249 ],
       [ 0.12105544, -1.06276296, -0.53131096]], shape=(1022, 3))

In [23]:
X_train[['age','avg_glucose_level','bmi']] = X_train_scaled
X_test[['age','avg_glucose_level','bmi']] = X_test_scaled

In [24]:
X_train.head()

,gender,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
845,0.0,0.209397,0,0,1,1,-0.821221,0.551632,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3745,0.0,-0.629845,0,0,0,1,-0.485884,-0.982537,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4184,0.0,-0.364822,0,0,1,0,0.302317,-0.763370,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3410,1.0,-0.232310,0,0,1,0,0.062342,0.500063,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
284,1.0,-1.292405,0,0,0,1,-0.527297,0.358249,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [25]:
X_test.head()

,gender,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
3667,0.0,-0.674016,1,0,1,0,-0.497748,0.977074,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2217,0.0,-1.778282,0,0,0,1,-0.281950,-1.201704,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
374,0.0,0.430250,0,0,1,0,-0.928896,0.280896,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2392,1.0,-0.364822,0,0,1,0,-0.820997,1.802173,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
299,0.0,0.651103,0,0,1,0,-0.259564,0.035945,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

## Now we **apply SVC**

In [26]:
from sklearn.svm import SVC

In [59]:
svc = SVC(kernel='rbf')
svc.fit(X_train,y_train)
y_prediction = svc.predict(X_test)

In [60]:
y_prediction

array([0, 0, 0, ..., 0, 0, 0], shape=(1022,))

In [65]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score,recall_score,f1_score
import warnings
warnings.filterwarnings('ignore')

In [66]:
print('Confusion Matrix: \n',confusion_matrix(y_test,y_prediction))

Confusion Matrix:
 [[972   0]
 [ 50   0]]

In [67]:
y_test.value_counts()

stroke
0    972
1     50
Name: count, dtype: int64

In [68]:
print(classification_report(y_test,y_prediction))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97       972
           1       0.00      0.00      0.00        50

    accuracy                           0.95      1022
   macro avg       0.48      0.50      0.49      1022
weighted avg       0.90      0.95      0.93      1022

### Class Weights

In [73]:
svc = SVC(kernel='rbf',class_weight={0:1,1:20})
svc.fit(X_train,y_train)

y_prediction = svc.predict(X_test)

print('Confusion Matrix: \n',confusion_matrix(y_test,y_prediction))
print(classification_report(y_test,y_prediction))

Confusion Matrix:
 [[746 226]
 [ 20  30]]
              precision    recall  f1-score   support

           0       0.97      0.77      0.86       972
           1       0.12      0.60      0.20        50

    accuracy                           0.76      1022
   macro avg       0.55      0.68      0.53      1022
weighted avg       0.93      0.76      0.83      1022

## **Upsampling and Downsampling to Improve the Result**

In [74]:
from imblearn.over_sampling import SMOTE

In [76]:
smote = SMOTE(random_state=42)

In [78]:
X_train_oversample,y_train_oversample = smote.fit_resample(X_train,y_train)

In [79]:
X_train_oversample

,gender,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,0.000000,0.209397,0,0,1,1,-0.821221,0.551632,0.0,0.0,1.000000,0.000000,0.0,0.000000,0.0,1.000000,0.0
1,0.000000,-0.629845,0,0,0,1,-0.485884,-0.982537,0.0,0.0,1.000000,0.000000,0.0,0.000000,0.0,1.000000,0.0
2,0.000000,-0.364822,0,0,1,0,0.302317,-0.763370,0.0,0.0,1.000000,0.000000,0.0,0.000000,0.0,1.000000,0.0
3,1.000000,-0.232310,0,0,1,0,0.062342,0.500063,0.0,0.0,1.000000,0.000000,0.0,0.000000,0.0,1.000000,0.0
4,1.000000,-1.292405,0,0,0,1,-0.527297,0.358249,1.0,0.0,0.000000,0.000000,0.0,1.000000,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7771,0.944898,1.215947,1,0,1,0,1.759486,1.023275,0.0,0.0,0.000000,1.000000,0.0,0.000000,0.0,1.000000,0.0
7772,0.000000,1.502743,0,0,1,1,-0.568139,-0.246624,0.0,0.0,1.000000,0.000000,0.0,0.000000,1.0,0.000000,0.0
7773,1.000000,0.938407,0,1,0,0,2.516775,-0.261261,1.0,0.0,0.000000,0.000000,0.0,0.530975,0.0,0.469025,0.0
7774,0.000000,0.117910,0,0,1,0,-0.250893,0.255129,0.0,0.0,1.000000,0.000000,0.0,0.000000,1.0,0.000000,0.0
7775,0.000000,1.622857,0,0,1,1,-0.764303,-0.519758,0.0,0.0,0.641086,0.358914,0.0,1.000000,0.0,0.000000,0.0

In [81]:
X_train.shape,X_train_oversample.shape

((4087, 17), (7776, 17))

In [82]:
y_train_oversample.value_counts()

stroke
0    3888
1    3888
Name: count, dtype: int64

### **SVC on Oversampled Data**

In [92]:
## for kernel = 'linear'
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(X_train_oversample,y_train_oversample)
y_pred = svc.predict(X_test)

print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Confusion Matrix:
 [[702 270]
 [ 11  39]]
              precision    recall  f1-score   support

           0       0.98      0.72      0.83       972
           1       0.13      0.78      0.22        50

    accuracy                           0.73      1022
   macro avg       0.56      0.75      0.53      1022
weighted avg       0.94      0.73      0.80      1022

In [89]:
# for kernel = 'poly'

svc = SVC(kernel='poly')
svc.fit(X_train_oversample,y_train_oversample)
y_pred = svc.predict(X_test)

print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Confusion Matrix:
 [[784 188]
 [ 28  22]]
              precision    recall  f1-score   support

           0       0.97      0.81      0.88       972
           1       0.10      0.44      0.17        50

    accuracy                           0.79      1022
   macro avg       0.54      0.62      0.52      1022
weighted avg       0.92      0.79      0.84      1022

In [90]:
# for kernel = 'rbf'

svc = SVC(kernel='rbf')
svc.fit(X_train_oversample,y_train_oversample)
y_pred = svc.predict(X_test)

print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Confusion Matrix:
 [[780 192]
 [ 28  22]]
              precision    recall  f1-score   support

           0       0.97      0.80      0.88       972
           1       0.10      0.44      0.17        50

    accuracy                           0.78      1022
   macro avg       0.53      0.62      0.52      1022
weighted avg       0.92      0.78      0.84      1022

In [91]:
# for kernel = 'sigmoid'

svc = SVC(kernel='sigmoid')
svc.fit(X_train_oversample,y_train_oversample)
y_pred = svc.predict(X_test)

print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Confusion Matrix:
 [[622 350]
 [ 15  35]]
              precision    recall  f1-score   support

           0       0.98      0.64      0.77       972
           1       0.09      0.70      0.16        50

    accuracy                           0.64      1022
   macro avg       0.53      0.67      0.47      1022
weighted avg       0.93      0.64      0.74      1022

* `This show that applying oversampling has imporve result for class 1 (patient having strokes)`
* `Specially for kernel = 'linear' for class 1, it is gving high result but overall for the other class it is making alot of error`

## **Downsampling**

In [102]:
X_train['stroke'] = y_train

In [ ]:
X_train['stroke'].value_counts()

stroke
0    3888
1     199
Name: count, dtype: int64

In [109]:
df_minority = X_train[X_train['stroke']==1]
df_majority = X_train[X_train['stroke']==0]

In [110]:
df_majority.shape,df_minority.shape

((3888, 18), (199, 18))

In [112]:
from sklearn.utils import resample
df_majority_downsampled = resample(df_majority,
                                    replace=False,
                                    n_samples=len(df_minority),
                                    random_state=42,
                                    )

In [116]:
### Concatinate Majority downsampled and Minorty downsampled
downsampled_df = pd.concat([df_majority_downsampled,df_minority],axis=0)

In [117]:
downsampled_df.shape

(398, 18)

In [118]:
downsampled_df.head()

,gender,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,stroke
4567,1.0,-1.424917,0,0,0,0,-0.305679,-0.118761,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0
1090,1.0,-0.585675,0,0,0,1,-0.386043,-0.853615,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0
2914,0.0,0.562762,0,0,1,1,-0.065480,0.023053,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0
297,1.0,0.651103,1,0,1,0,-1.095446,-0.260575,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
445,1.0,-1.336576,0,0,0,0,-1.130592,-0.724694,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0

In [120]:
downsampled_df = downsampled_df.sample(frac=1)   ## Shuffling the dataframe 
downsampled_df.head()

,gender,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,stroke
1307,0.0,-0.806528,0,0,0,0,-0.292695,-0.608664,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0
4567,1.0,-1.424917,0,0,0,0,-0.305679,-0.118761,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0
4410,1.0,-1.336576,0,0,0,1,-0.465960,-1.833421,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
2228,1.0,0.209397,1,0,1,1,1.770819,-0.350820,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0
196,1.0,1.181151,1,0,1,0,3.058444,2.150262,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1

In [124]:
X_train_downsampled = downsampled_df.iloc[:,:-1]
y_train_downsampled = downsampled_df.iloc[:,-1]

In [125]:
X_train_downsampled.shape

(398, 17)

In [126]:
y_train_downsampled.shape

(398,)

### **Training SVM on Downsampled Data**

In [127]:
svc = SVC(kernel='linear')
svc.fit(X_train_downsampled,y_train_downsampled)
y_pred = svc.predict(X_test)

print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Confusion Matrix:
 [[657 315]
 [  8  42]]
              precision    recall  f1-score   support

           0       0.99      0.68      0.80       972
           1       0.12      0.84      0.21        50

    accuracy                           0.68      1022
   macro avg       0.55      0.76      0.50      1022
weighted avg       0.95      0.68      0.77      1022

In [128]:
svc = SVC(kernel='sigmoid')
svc.fit(X_train_downsampled,y_train_downsampled)
y_pred = svc.predict(X_test)

print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Confusion Matrix:
 [[627 345]
 [ 13  37]]
              precision    recall  f1-score   support

           0       0.98      0.65      0.78       972
           1       0.10      0.74      0.17        50

    accuracy                           0.65      1022
   macro avg       0.54      0.69      0.47      1022
weighted avg       0.94      0.65      0.75      1022

In [129]:
svc = SVC(kernel='rbf')
svc.fit(X_train_downsampled,y_train_downsampled)
y_pred = svc.predict(X_test)

print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Confusion Matrix:
 [[635 337]
 [ 10  40]]
              precision    recall  f1-score   support

           0       0.98      0.65      0.79       972
           1       0.11      0.80      0.19        50

    accuracy                           0.66      1022
   macro avg       0.55      0.73      0.49      1022
weighted avg       0.94      0.66      0.76      1022

In [130]:
svc = SVC(kernel='poly')
svc.fit(X_train_downsampled,y_train_downsampled)
y_pred = svc.predict(X_test)

print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Confusion Matrix:
 [[718 254]
 [ 13  37]]
              precision    recall  f1-score   support

           0       0.98      0.74      0.84       972
           1       0.13      0.74      0.22        50

    accuracy                           0.74      1022
   macro avg       0.55      0.74      0.53      1022
weighted avg       0.94      0.74      0.81      1022

In [133]:
svc = SVC(kernel='poly')
svc.fit(X_train_downsampled,y_train_downsampled)
y_pred = svc.predict(X_test)

print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Confusion Matrix:
 [[718 254]
 [ 13  37]]
              precision    recall  f1-score   support

           0       0.98      0.74      0.84       972
           1       0.13      0.74      0.22        50

    accuracy                           0.74      1022
   macro avg       0.55      0.74      0.53      1022
weighted avg       0.94      0.74      0.81      1022